Capstone.Web/Controllers/AuthenticationController.cs
using Capstone.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using Capstone.Core.Entities;

namespace Capstone.Web.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly IAuthenticationRepository _authRepository;

        public AuthenticationController(IAuthenticationRepository authRepository)
        {
            _authRepository = authRepository;
        }

        [HttpGet]
        [Route("/[controller]")]
        public IActionResult Index()
        {
            var loginResults = _authRepository.GetAll();
            return View(loginResults.Data);
        }

        [HttpGet]
        [Route("/[controller]/{id}")]
        public IActionResult Get(Guid id)
        {
            var agency = _authRepository.Get(id);

            if (agency.Success)
            {
                return View(agency.Data);
            }
            else
            {
                Response.StatusCode = 404;
                return View("NotFound");
            }
        }

        [HttpGet]
        [Route("[controller]/update")]
        public IActionResult Update(Guid id)
        {
            var loginResult = _authRepository.Get(id);

            return View(loginResult.Data);
        }

        [HttpPost]
        [Route("[controller]/update")]
        public IActionResult Update(LoginItem model)
        {
            var agency = _authRepository.Update(model);

            if (agency.Success)
            {
                return RedirectToAction("Index");
            }
            else
            {
                Response.StatusCode = 404;
                return View("NotFound");
            }
        }

        [HttpGet]
        [Route("[controller]/add")]
        public IActionResult Add()
        {
            var loginItem = new LoginItem();
            return View(loginItem);
        }

        [HttpPost]
        [Route("[controller]/add")]
        public IActionResult Add(LoginItem model)
        {
            var agency = _authRepository.Create(model);

            if (agency.Success)
            {
                return RedirectToAction("Index");
            }
            else
            {
                Response.StatusCode = 404;
                return View("NotFound");
            }
        }

        [HttpGet]
        [Route("[controller]/remove/{id}")]
        public IActionResult Delete(Guid id)
        {
            var agency = _authRepository.Get(id);
            return View(agency.Data);
        }

        [HttpPost]
        [Route("[controller]/remove/{id}")]
        public IActionResult Delete(LoginItem model)
        {
            var agency = _authRepository.Delete(model.Id);

            if (agency.Success)
            {
                return RedirectToAction("Index");
            }
            else
            {
                Response.StatusCode = 404;
                return View("NotFound");
            }
        }

        [Route("[controller]/NotFound")]
        public IActionResult NotFound()
        {
            Response.StatusCode = 404;  //you may want to set this to 200
            return View("NotFound");
        }
    }
}

Capstone.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

using System.Linq;
using System.Threading.Tasks;
using Capstone.Web.Models;


namespace Capstone.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Route("/")]
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Login()
        {
            return Redirect("http://localhost:4200/login");
        }
    }
}

Capstone.Web/Controllers/ReportsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Capstone.Core.Interfaces;

namespace Capstone.Web.Controllers
{
    public class ReportsController : Controller
    {
        private readonly IReportRepository _reportRepository;

        public ReportsController(IReportRepository reportRepository)
        {
            _reportRepository = reportRepository;
        }

        [Route("reports")]
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [Route("reports/largesthealthpools")]
        [HttpGet]
        public IActionResult LargestHealthPools()
        {
            var result = _reportRepository.GetCharactersByHealthPool();

            if (result.Success) return View(result.Data);

            throw new Exception(result.Message);
        }

        [Route("reports/longestcampaigns")]
        [HttpGet]
        public IActionResult LongestCampaigns()
        {
            var result = _reportRepository.GetLongestCampaigns();

            if (result.Success) return View(result.Data);

            throw new Exception(result.Message);
        }
    }
}

Capstone.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-white">
    <h1 class="mb-4"><i class="fa-brands fa-d-and-d"></i> Campaign Manager <i class="fa-brands fa-d-and-d"></i></h1>
    <div class="row">
        <div class="col-sm-3 d-flex align-items-stretch text-white">
            @* ----------------------Campaign Manager---------------------- *@
            <div class="card border border-secondary" style="height: 14rem; background-color: #0e2431;">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">Campaign Manager</h5>
                    <p class="card-text">Create and manage your Dungeons & Dragons campaigns. <i style="color: #ffc107">Click button to login.</i></p>
                    <a type="button" class="btn btn-outline-light mt-auto align-self-start" asp-action="Login" asp-controller="Home">Go to page</a>
                </div>
            </div>
        </div>
        <div class="col-sm-3 d-flex align-items-stretch text-white">
            @* ----------------------Reports---------------------- *@
            <div class="card border border-secondary" style="height: 14rem; background-color: #0e2431;">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">Reports</h5>
                    <p class="card-text">High level reporting and overview for existing campaigns</p>
                    <a type="button" class="btn btn-outline-light mt-auto align-self-start" asp-action="Index" asp-controller="Reports">Go to page</a>
                </div>
            </div>
        </div>
        <div class="col-sm-3 d-flex align-items-stretch text-white">
            @* ----------------------Authentication---------------------- *@
            <div class="card border border-secondary" style="height: 14rem; background-color: #0e2431;">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">Authentication</h5>
                    <p class="card-text">Login users administration</p>
                    <a type="button" class="btn btn-outline-light mt-auto align-self-start" asp-action="Index" asp-controller="Authentication">Go to page</a>
                </div>
            </div>
        </div>
    </div>
</div>